apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react-webapp 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-webapp
  template:
    metadata:
      labels:
        app: react-webapp
    spec:
      containers:
      - name: react-webapp 
        image: rohaanraj/react-nginx-webapp:2
        ports:
        - containerPort: 80
